package storage

import (
	"bytes"
	"context"
	"fmt"
	"io"

	"github.com/minio/minio-go/v7"
)

// GetObject fetches an object's bytes directly (via the internal
// docker-network client) — used server-side by nimbus-worker to reassemble
// original chunks for thumbnail generation (docs/02-system-design.md §6).
// Unlike PresignGet, this reads the object itself rather than handing a
// URL to an external caller, so the internal endpoint is the right one.
func (rt *Router) GetObject(ctx context.Context, node NodeID, key string) (io.ReadCloser, error) {
	rt.mu.RLock()
	cli := rt.internalMinio[node]
	rt.mu.RUnlock()
	if cli == nil {
		return nil, fmt.Errorf("no internal MinIO client for node %s", node)
	}
	return cli.GetObject(ctx, bucketName, key, minio.GetObjectOptions{})
}

// PutObject stores server-generated bytes (e.g. a thumbnail) directly via
// the internal client — the counterpart to GetObject.
func (rt *Router) PutObject(ctx context.Context, node NodeID, key string, data []byte, contentType string) error {
	rt.mu.RLock()
	cli := rt.internalMinio[node]
	rt.mu.RUnlock()
	if cli == nil {
		return fmt.Errorf("no internal MinIO client for node %s", node)
	}
	_, err := cli.PutObject(ctx, bucketName, key, bytes.NewReader(data), int64(len(data)), minio.PutObjectOptions{ContentType: contentType})
	return err
}
