apiVersion: v1
kind: Secret
metadata:
  name: nimbus-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  NIMBUS_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  NIMBUS_MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  NIMBUS_MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  NIMBUS_ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  NIMBUS_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
